const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'app', 'content-manager', 'page.tsx');
const t = fs.readFileSync(filePath, 'utf8');
const lines = t.split('\n');

// Find the range: first line with "form.hasXray && (" after the toggles section
// to the closing </div> of the old Lab Results section (line before "Diagnosis & Treatment")
const startIdx = lines.findIndex(l => l.includes('{form.hasXray && ('));
const endIdx = lines.findIndex((l, i) => i > startIdx + 5 && l.includes('removeLabRow(i)'));

// Find the actual closing div after removeLabRow block
// We need to go to the line that closes the outer lab div
// From reading: removeLabRow is near line 561, the outer div closes around line 569
let labEnd = endIdx;
while (labEnd < lines.length && !lines[labEnd].trimStart().startsWith('</div>') ||
       (lines[labEnd].trimStart().startsWith('</div>') && lines[labEnd].indexOf('\t') < 5)) {
  labEnd++;
}
// Make sure we're at the right closing div (5-tab level: "\t\t\t\t\t</div>")
while (labEnd < lines.length) {
  if (lines[labEnd] === '\t\t\t\t\t</div>') break;
  labEnd++;
}

if (startIdx === -1) { console.error('startIdx not found'); process.exit(1); }
if (labEnd === lines.length) { console.error('labEnd not found'); process.exit(1); }

console.log('Replacing lines', startIdx + 1, 'to', labEnd + 1);

const T = '\t';
const newBlock = [
T.repeat(6) + `{/* KT / Rentgen multi-file section */}`,
T.repeat(6) + `{form.hasXray && (`,
T.repeat(7) + `<div className='mb-4 p-4 bg-surface-light rounded-xl border border-border'>`,
T.repeat(8) + `<div className='flex items-center justify-between mb-3'>`,
T.repeat(9) + `<p className='text-sm font-medium text-text-primary'>KT / Rentgen rasmlari</p>`,
T.repeat(9) + `{uploading === 'xray' && <Loader2 className='w-4 h-4 animate-spin text-primary' />}`,
T.repeat(8) + `</div>`,
T.repeat(8) + `{xrayItems.length > 0 && (`,
T.repeat(9) + `<div className='space-y-3 mb-3'>`,
T.repeat(10) + `{xrayItems.map((item, i) => (`,
T.repeat(11) + `<div key={i} className='bg-surface rounded-lg p-2 border border-border'>`,
T.repeat(12) + `<div className='flex items-center justify-between mb-1'>`,
T.repeat(13) + `<p className='text-xs text-text-secondary truncate max-w-[70%]'>{item.fileName}</p>`,
T.repeat(13) + `<button type='button' onClick={() => removeMedia('xray', i)} className='text-accent hover:text-accent/80'><X className='w-3.5 h-3.5' /></button>`,
T.repeat(12) + `</div>`,
T.repeat(12) + `<img src={item.fileData.startsWith('http') || item.fileData.startsWith('data:') ? item.fileData : \`\${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}\${item.fileData}\`} alt={\`xray-\${i}\`} className='w-full h-28 object-contain rounded bg-black mb-2' />`,
T.repeat(12) + `<textarea value={item.comment} onChange={e => updateMediaComment('xray', i, e.target.value)} rows={2} placeholder='KT/Rentgen xulosasi (majburiy)...'`,
T.repeat(13) + `className='w-full bg-surface-light border border-border rounded-lg px-2 py-1.5 text-xs text-text-primary focus:outline-none focus:ring-1 focus:ring-primary/50 resize-none' />`,
T.repeat(11) + `</div>`,
T.repeat(10) + `))}`,
T.repeat(9) + `</div>`,
T.repeat(8) + `)}`,
T.repeat(8) + `<button type='button' onClick={() => xrayRef.current?.click()} disabled={!!uploading}`,
T.repeat(9) + `className='w-full h-16 border-2 border-dashed border-border rounded-xl flex items-center justify-center gap-2 text-text-secondary hover:border-primary/50 hover:text-primary transition-colors text-xs disabled:opacity-50'>`,
T.repeat(9) + `<Upload className='w-4 h-4' /> {xrayItems.length > 0 ? "Ko'proq qo'shish" : 'KT/Rentgen rasmini yuklang (rasm yoki GIF)'}`,
T.repeat(8) + `</button>`,
T.repeat(8) + `<input ref={xrayRef} type='file' accept='image/*,.gif' multiple className='hidden' onChange={e => handleFilesChange('xray', e.target.files)} />`,
T.repeat(7) + `</div>`,
T.repeat(6) + `)}`,
``,
T.repeat(6) + `{/* EKG multi-file section */}`,
T.repeat(6) + `{form.hasEkg && (`,
T.repeat(7) + `<div className='mb-4 p-4 bg-surface-light rounded-xl border border-border'>`,
T.repeat(8) + `<div className='flex items-center justify-between mb-3'>`,
T.repeat(9) + `<p className='text-sm font-medium text-text-primary'>EKG rasmlari</p>`,
T.repeat(9) + `{uploading === 'ekg' && <Loader2 className='w-4 h-4 animate-spin text-primary' />}`,
T.repeat(8) + `</div>`,
T.repeat(8) + `{ekgItems.length > 0 && (`,
T.repeat(9) + `<div className='space-y-3 mb-3'>`,
T.repeat(10) + `{ekgItems.map((item, i) => (`,
T.repeat(11) + `<div key={i} className='bg-surface rounded-lg p-2 border border-border'>`,
T.repeat(12) + `<div className='flex items-center justify-between mb-1'>`,
T.repeat(13) + `<p className='text-xs text-text-secondary truncate max-w-[70%]'>{item.fileName}</p>`,
T.repeat(13) + `<button type='button' onClick={() => removeMedia('ekg', i)} className='text-accent hover:text-accent/80'><X className='w-3.5 h-3.5' /></button>`,
T.repeat(12) + `</div>`,
T.repeat(12) + `<img src={item.fileData.startsWith('http') || item.fileData.startsWith('data:') ? item.fileData : \`\${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}\${item.fileData}\`} alt={\`ekg-\${i}\`} className='w-full h-28 object-contain rounded bg-black mb-2' />`,
T.repeat(12) + `<textarea value={item.comment} onChange={e => updateMediaComment('ekg', i, e.target.value)} rows={2} placeholder='EKG xulosasi (majburiy)...'`,
T.repeat(13) + `className='w-full bg-surface-light border border-border rounded-lg px-2 py-1.5 text-xs text-text-primary focus:outline-none focus:ring-1 focus:ring-primary/50 resize-none' />`,
T.repeat(11) + `</div>`,
T.repeat(10) + `))}`,
T.repeat(9) + `</div>`,
T.repeat(8) + `)}`,
T.repeat(8) + `<button type='button' onClick={() => ekgRef.current?.click()} disabled={!!uploading}`,
T.repeat(9) + `className='w-full h-16 border-2 border-dashed border-border rounded-xl flex items-center justify-center gap-2 text-text-secondary hover:border-primary/50 hover:text-primary transition-colors text-xs disabled:opacity-50'>`,
T.repeat(9) + `<ImagePlus className='w-4 h-4' /> {ekgItems.length > 0 ? "Ko'proq qo'shish" : 'EKG rasmini yuklang (rasm yoki GIF)'}`,
T.repeat(8) + `</button>`,
T.repeat(8) + `<input ref={ekgRef} type='file' accept='image/*,.gif' multiple className='hidden' onChange={e => handleFilesChange('ekg', e.target.files)} />`,
T.repeat(7) + `</div>`,
T.repeat(6) + `)}`,
``,
T.repeat(6) + `{/* EXO multi-file section */}`,
T.repeat(6) + `{form.hasEcho && (`,
T.repeat(7) + `<div className='mb-4 p-4 bg-surface-light rounded-xl border border-border'>`,
T.repeat(8) + `<div className='flex items-center justify-between mb-3'>`,
T.repeat(9) + `<p className='text-sm font-medium text-text-primary'>EXO rasmlari</p>`,
T.repeat(9) + `{uploading === 'echo' && <Loader2 className='w-4 h-4 animate-spin text-primary' />}`,
T.repeat(8) + `</div>`,
T.repeat(8) + `{echoItems.length > 0 && (`,
T.repeat(9) + `<div className='space-y-3 mb-3'>`,
T.repeat(10) + `{echoItems.map((item, i) => (`,
T.repeat(11) + `<div key={i} className='bg-surface rounded-lg p-2 border border-border'>`,
T.repeat(12) + `<div className='flex items-center justify-between mb-1'>`,
T.repeat(13) + `<p className='text-xs text-text-secondary truncate max-w-[70%]'>{item.fileName}</p>`,
T.repeat(13) + `<button type='button' onClick={() => removeMedia('echo', i)} className='text-accent hover:text-accent/80'><X className='w-3.5 h-3.5' /></button>`,
T.repeat(12) + `</div>`,
T.repeat(12) + `<img src={item.fileData.startsWith('http') || item.fileData.startsWith('data:') ? item.fileData : \`\${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}\${item.fileData}\`} alt={\`echo-\${i}\`} className='w-full h-28 object-contain rounded bg-black mb-2' />`,
T.repeat(12) + `<textarea value={item.comment} onChange={e => updateMediaComment('echo', i, e.target.value)} rows={2} placeholder='EXO xulosasi (majburiy)...'`,
T.repeat(13) + `className='w-full bg-surface-light border border-border rounded-lg px-2 py-1.5 text-xs text-text-primary focus:outline-none focus:ring-1 focus:ring-primary/50 resize-none' />`,
T.repeat(11) + `</div>`,
T.repeat(10) + `))}`,
T.repeat(9) + `</div>`,
T.repeat(8) + `)}`,
T.repeat(8) + `<button type='button' onClick={() => echoRef.current?.click()} disabled={!!uploading}`,
T.repeat(9) + `className='w-full h-16 border-2 border-dashed border-border rounded-xl flex items-center justify-center gap-2 text-text-secondary hover:border-primary/50 hover:text-primary transition-colors text-xs disabled:opacity-50'>`,
T.repeat(9) + `<ImagePlus className='w-4 h-4' /> {echoItems.length > 0 ? "Ko'proq qo'shish" : 'EXO rasmini yuklang (rasm yoki GIF)'}`,
T.repeat(8) + `</button>`,
T.repeat(8) + `<input ref={echoRef} type='file' accept='image/*,.gif' multiple className='hidden' onChange={e => handleFilesChange('echo', e.target.files)} />`,
T.repeat(7) + `</div>`,
T.repeat(6) + `)}`,
``,
T.repeat(6) + `{/* Additional image (single) */}`,
T.repeat(6) + `<div className='pt-2'>`,
T.repeat(7) + `<p className='text-xs font-semibold text-text-secondary mb-2'>Qo&apos;shimcha rasm (ixtiyoriy)</p>`,
T.repeat(7) + `{imageItem ? (`,
T.repeat(8) + `<div className='p-3 bg-surface-light rounded-xl border border-border'>`,
T.repeat(9) + `<div className='flex items-center justify-between mb-2'>`,
T.repeat(10) + `<p className='text-xs font-medium text-text-primary truncate max-w-[70%]'>{imageItem.fileName}</p>`,
T.repeat(10) + `<button type='button' onClick={() => removeMedia('image')} className='text-accent hover:text-accent/80'><X className='w-4 h-4' /></button>`,
T.repeat(9) + `</div>`,
T.repeat(9) + `<img src={imageItem.fileData.startsWith('http') || imageItem.fileData.startsWith('data:') ? imageItem.fileData : \`\${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}\${imageItem.fileData}\`} alt='img' className='w-full h-28 object-contain rounded-lg mb-2 bg-black/30' />`,
T.repeat(9) + `<textarea value={imageItem.comment} onChange={e => updateMediaComment('image', 0, e.target.value)} rows={1} placeholder='Izoh...'`,
T.repeat(10) + `className='w-full bg-surface border border-border rounded-xl px-3 py-1.5 text-sm text-text-primary focus:outline-none focus:ring-2 focus:ring-primary/50 resize-none' />`,
T.repeat(8) + `</div>`,
T.repeat(7) + `) : (`,
T.repeat(8) + `<button type='button' onClick={() => imageRef.current?.click()} disabled={!!uploading}`,
T.repeat(9) + `className='w-full h-16 border-2 border-dashed border-border rounded-xl flex items-center justify-center gap-2 text-text-secondary hover:border-primary/50 hover:text-primary transition-colors text-xs disabled:opacity-50'>`,
T.repeat(9) + `<ImagePlus className='w-4 h-4' /> Rasm yoki GIF yuklang`,
T.repeat(8) + `</button>`,
T.repeat(7) + `)}`,
T.repeat(7) + `<input ref={imageRef} type='file' accept='image/*,.gif' className='hidden' onChange={e => handleFilesChange('image', e.target.files)} />`,
T.repeat(6) + `</div>`,
``,
T.repeat(6) + `{/* Video (single) */}`,
T.repeat(6) + `<div className='pt-2'>`,
T.repeat(7) + `<p className='text-xs font-semibold text-text-secondary mb-2'>Video (ixtiyoriy)</p>`,
T.repeat(7) + `{videoItem ? (`,
T.repeat(8) + `<div className='p-3 bg-surface-light rounded-xl border border-border'>`,
T.repeat(9) + `<div className='flex items-center justify-between mb-2'>`,
T.repeat(10) + `<p className='text-xs font-medium text-text-primary truncate max-w-[70%]'>{videoItem.fileName}</p>`,
T.repeat(10) + `<button type='button' onClick={() => removeMedia('video')} className='text-accent hover:text-accent/80'><X className='w-4 h-4' /></button>`,
T.repeat(9) + `</div>`,
T.repeat(9) + `<video src={videoItem.fileData.startsWith('http') || videoItem.fileData.startsWith('data:') ? videoItem.fileData : \`\${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}\${videoItem.fileData}\`} controls className='w-full rounded-lg mb-2 max-h-32' />`,
T.repeat(9) + `<textarea value={videoItem.comment} onChange={e => updateMediaComment('video', 0, e.target.value)} rows={1} placeholder='Izoh...'`,
T.repeat(10) + `className='w-full bg-surface border border-border rounded-xl px-3 py-1.5 text-sm text-text-primary focus:outline-none focus:ring-2 focus:ring-primary/50 resize-none' />`,
T.repeat(8) + `</div>`,
T.repeat(7) + `) : (`,
T.repeat(8) + `<button type='button' onClick={() => videoRef.current?.click()} disabled={!!uploading}`,
T.repeat(9) + `className='w-full h-16 border-2 border-dashed border-border rounded-xl flex items-center justify-center gap-2 text-text-secondary hover:border-primary/50 hover:text-primary transition-colors text-xs disabled:opacity-50'>`,
T.repeat(9) + `<Upload className='w-4 h-4' /> Video yuklang (mp4, webm)`,
T.repeat(8) + `</button>`,
T.repeat(7) + `)}`,
T.repeat(7) + `<input ref={videoRef} type='file' accept='video/*' className='hidden' onChange={e => handleFilesChange('video', e.target.files)} />`,
T.repeat(6) + `</div>`,
T.repeat(5) + `</div>`,
``,
T.repeat(5) + `{/* Lab Results - three typed sections */}`,
T.repeat(5) + `<div className='border-t border-border pt-4 space-y-5'>`,
T.repeat(6) + `<p className='text-sm font-semibold text-text-primary'>Laboratoriya bo&apos;limlari</p>`,
T.repeat(6) + `{LAB_SECTIONS.map(({ key, label }) => (`,
T.repeat(7) + `<div key={key}>`,
T.repeat(8) + `<div className='flex items-center justify-between mb-2'>`,
T.repeat(9) + `<p className='text-xs font-semibold text-text-secondary'>{label}</p>`,
T.repeat(9) + `<button type='button' onClick={() => addSectionRow(key)}`,
T.repeat(10) + `className='flex items-center gap-1 text-xs text-primary hover:text-primary/80 transition-colors'>`,
T.repeat(10) + `<Plus className='w-3.5 h-3.5' /> Qo&apos;shish`,
T.repeat(9) + `</button>`,
T.repeat(8) + `</div>`,
T.repeat(8) + `{form[key].length > 0 && (`,
T.repeat(9) + `<div className='space-y-2'>`,
T.repeat(10) + `{form[key].map((row, i) => (`,
T.repeat(11) + `<div key={i} className='grid grid-cols-5 gap-2 items-center'>`,
T.repeat(12) + `<input value={row.name} onChange={e => updateSectionRow(key, i, 'name', e.target.value)} placeholder={"Ko'rsatkich"}`,
T.repeat(13) + `className='col-span-2 bg-surface-light border border-border rounded-lg px-2 py-1.5 text-xs text-text-primary focus:outline-none focus:ring-1 focus:ring-primary/50' />`,
T.repeat(12) + `<input value={row.value} onChange={e => updateSectionRow(key, i, 'value', e.target.value)} placeholder='Qiymat'`,
T.repeat(13) + `className='bg-surface-light border border-border rounded-lg px-2 py-1.5 text-xs text-text-primary focus:outline-none focus:ring-1 focus:ring-primary/50' />`,
T.repeat(12) + `<input value={row.unit} onChange={e => updateSectionRow(key, i, 'unit', e.target.value)} placeholder='Birlik'`,
T.repeat(13) + `className='bg-surface-light border border-border rounded-lg px-2 py-1.5 text-xs text-text-primary focus:outline-none focus:ring-1 focus:ring-primary/50' />`,
T.repeat(12) + `<div className='flex items-center gap-1'>`,
T.repeat(13) + `<select value={row.status} onChange={e => updateSectionRow(key, i, 'status', e.target.value)}`,
T.repeat(14) + `className='flex-1 bg-surface-light border border-border rounded-lg px-1 py-1.5 text-xs text-text-primary focus:outline-none focus:ring-1 focus:ring-primary/50'>`,
T.repeat(14) + `<option value='normal'>Normal</option>`,
T.repeat(14) + `<option value='high'>Yuqori</option>`,
T.repeat(14) + `<option value='low'>Past</option>`,
T.repeat(14) + `<option value='critical'>Kritik</option>`,
T.repeat(13) + `</select>`,
T.repeat(13) + `<button type='button' onClick={() => removeSectionRow(key, i)} className='text-accent hover:text-accent/80 shrink-0'>`,
T.repeat(14) + `<X className='w-3.5 h-3.5' />`,
T.repeat(13) + `</button>`,
T.repeat(12) + `</div>`,
T.repeat(11) + `</div>`,
T.repeat(10) + `))}`,
T.repeat(9) + `</div>`,
T.repeat(8) + `)}`,
T.repeat(7) + `</div>`,
T.repeat(6) + `))}`,
T.repeat(5) + `</div>`,
].join('\n');

const before = lines.slice(0, startIdx).join('\n');
const after = lines.slice(labEnd + 1).join('\n');
const result = before + '\n' + newBlock + '\n' + after;
fs.writeFileSync(filePath, result, 'utf8');
console.log('Done. Replaced lines', startIdx + 1, 'to', labEnd + 1, '-> new code written.');
